# .github/workflows/main.yml
name: CICD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_and_test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tao JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven.
      - name: Khoi tao va chay Unit Test
        run: mvn clean verify

      #1
      #        git init
      #        git remote add origin [URL_REPO]
      #        git add .
      #        git commit -m "KhoiTao"
      #        git push -u origin master

      #2
      #       git add .github/workflows/main.yml
      #       git commit -m "Add CI workflow"
      #       git push origi master


    #Push file thuong
    #     git add .
    # Hoac: git add ten_file_cu_the.java
    #     git commit -m "Mô tả"
    #     git push origin master